spring:
  datasource:
    url: jdbc:mysql://120.78.216.226:3306/stmanage?characterEncoding=UTF-8&useAffectedRows=true #url
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  transaction:
    rollback-on-commit-failure: true
  thymeleaf:
    cache: false
  druid:
    initial-size: 1
    min-idle: 1
    max-active: 20
    test-on-borrow: true
    start-view-servlet:
      allow: true
  mvc:
    static-path-pattern: /static/**
    static-locations: classpath:/templates/,classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
  devtools:
    restart:
      #热部署生效
      enabled: true
      #设置重启的目录
      additional-paths: src/main/java
      #该目录下的内容修改不重启
      exclude: resources/**,static/**,templates/**,luaFile/**
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.st.newtest.Entity
  configuration:
    #map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #log-impl: org.apache.ibatis.logging.log4j2.Log4j2Impl
    mapUnderscoreToCamelCase: true # 开启驼峰命名转换法
logging:
  config: classpath:log4j2.xml
  level:
    com.st.newtest.Mapper: TRACE
    com.st.newtest.stGame.Mapper: TRACE
    com.st.newtest.systemManage.Mapper: DEBUG
server:
  port: 8080