spring:
  datasource:
    url: jdbc:mysql://120.78.216.226:3306/stmanage?characterEncoding=UTF-8 #url
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    prefix: classpath:/templates/
  druid:
    initial-size: 1
    min-idle: 1
    max-active: 20
    test-on-borrow: true
    start-view-servlet:
      allow: true
  mvc:
    static-path-pattern: /static/**
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.st.newtest.Entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
mapper:
  mappers: com.st.newtest.Util.MyMapper
  not-empty: false
  identity: MYSQL
logging:
  config: classpath:log4j2.xml
  level:
    com:
      st:
        newtest:
          mapper: debug